bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('storeadmin/',include('storeadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *
app_name="store"
urlpatterns=[
    path('',HomeView.as_view(),name="home"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('cart/',CartView.as_view(),name="cart"),
    path('register/',RegisterView.as_view(),name="register"),
    path('confirm-email/<str:token>/',ConfirmEmail.as_view(),name="confirm"),
    path('login/otpcode/',OTPVerification.as_view(),name="otpverify"),
    path('bookdetail/<int:book_id>/',BookDetail.as_view(),name="bookdetail"),
]

store/models.py
from django.db import models
from django.contrib.auth import get_user_model
User=get_user_model()
import uuid
from django.utils import timezone
# Create your models here.
class Author(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.name
class Genre(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self) -> str:
        return self.name
class Book(models.Model):
    title=models.CharField(max_length=100)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)
    genre=models.ForeignKey(Genre,on_delete=models.CASCADE)
    price=models.IntegerField()
    description=models.TextField()
    book_image=models.ImageField()
    def __str__(self) -> str:
        return self.title
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    items=models.ForeignKey(Book,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    def __str__(self)->str:
        return "user:"+str(self.user)+" order";
class EmailTokenGeneration(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    token=models.UUIDField(default=uuid.uuid4,editable=False,unique=True)
    created_at=models.DateField(default=timezone.now)
    def __str__(self) -> str:
        return str(self.token)
class Comment(models.Model):
    value=models.TextField(blank=False)
    comment_user=models.ForeignKey(User,on_delete=models.CASCADE)
    book=models.ForeignKey(Book,on_delete=models.CASCADE)

store/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from .models import EmailTokenGeneration
class LoginForm(forms.Form):
   email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError("This email address is already in use.")
        return cleaned_data
    def save(self,commit=True):
        user=super().save(commit=False)
        if commit:
            user.is_active=False
            user.save()
            token=EmailTokenGeneration.objects.create(user=user)
            email_confirmation(user,token)
        return user
def email_confirmation(user,email_token):
    subject="Confirm Your Email"
    message=render_to_string('store/email_confirm.html',{
        'user':user,
        'confirm_url':f'http://merobook.onrender.com//confirm-email/{email_token}/'
    })
    from_email = settings.EMAIL_HOST_USER
    to_email = user.email
    send_mail(subject,message,from_email,[to_email],fail_silently=False)
class OTPform(forms.Form):
    otpvalue=forms.CharField(label='Enter OTP',widget=forms.TextInput(attrs={'class':'form-control'}))

store/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
import pyotp
from django.conf import settings
from django.core.mail import send_mail
@method_decorator(login_required(login_url='store:login'),name="dispatch")
class HomeView(View):
    def get(self,request):
        genre_id = request.GET.get('genre')
        book_val=request.GET.get('searckBook')
        if genre_id is None and book_val is None:
            books=Book.objects.all()
        elif genre_id is not None:
            books = Book.objects.filter(genre_id=genre_id)
        else:
            books = Book.objects.filter(title__icontains=book_val)
        genre=Genre.objects.all()
        return render(request,'store/home.html',{'books':books,'genre':genre,'messages':''})
    def post(self,request):
        book_id=request.POST.get('book_id')
        try:
            check_cart=Cart.objects.get(user=request.user, items__id=book_id)
            if check_cart is not None:
                check_cart.quantity+=1
                check_cart.save()
                messages='Cart incremented successfully.'
            else:
                new_cart=Cart.objects.create(user=request.user, items_id=book_id)
                new_cart.save()
                messages='New item added to the cart.'
        except:
            new_cart=Cart.objects.create(user=request.user, items_id=book_id)
            new_cart.save()
            messages='New item added to the cart.'
        books=Book.objects.all()
        genre=Genre.objects.all()
        return render(request,'store/home.html',{'books':books,'genre':genre,'messages':messages})
@method_decorator(login_required(login_url='store:login'),name="dispatch")
class CartView(View):
    def get(self,request):
        cart_items=Cart.objects.filter(user=request.user)
        cart_items_dict = {}
        for cart_item in cart_items:
            book_values = {
                "title": cart_item.items.title,  
                "price": cart_item.items.price,
                "book_image": cart_item.items.book_image.url,
                "quantity": cart_item.quantity,
            }
            cart_items_dict[cart_item.id] = book_values
        return render(request,'store/cart.html',{'cart':cart_items_dict})
    def post(self,request):
        cart_items=Cart.objects.filter(user=request.user)
        book_ordered=""
        coupon=request.POST.get('coupon')
        for cart_item in cart_items:
            title=cart_item.items.title
            quantity=cart_item.quantity
            price=cart_item.items.price*quantity
            book_ordered+=f"Name:{title} Quantity:{quantity} Price:{price}\n"
        book_ordered+=f"coupon:{coupon}"
        subject="Book Ordered"
        send_mail(subject,book_ordered,settings.EMAIL_HOST_USER,[request.user.email])
        cart_items.delete()
        return render(request,'store/cart.html',{'cart':''})
class LoginView(View):
    def get(self,request):
        return render(request,'login.html',{'form':LoginForm()})
    def post(self,request):
        loginVal=LoginForm(request.POST)
        if loginVal.is_valid():
            email=loginVal.cleaned_data['email']
            password=loginVal.cleaned_data['password']
            getUser=authenticate(email=email,password=password)
            if getUser is not None:
                secret_key = pyotp.random_base32()
                motp=pyotp.TOTP(secret_key)
                otp=motp.now()
                request.session['otp']=otp
                request.session['otp_user']=getUser.id
                send_mail("OTP Number",f"Your OTP is {otp}",settings.EMAIL_HOST_USER,[email])
                return redirect("store:otpverify")
        loginVal.add_error(None,'Error Email or password')
        return render(request,'login.html',{'form':loginVal})
class OTPVerification(View):
    def get(self,request):
        return render(request,'store/otpverify.html',{'form':OTPform})
    def post(self,request):
        otpform=OTPform(request.POST)
        if otpform.is_valid():
            otp=otpform.cleaned_data['otpvalue']
            otp_in_session=request.session.get('otp')
            otp_user=request.session.get('otp_user')
            if otp_user is None:
                return redirect('store:login')
            if otp==otp_in_session:
                user = User.objects.get(id=otp_user)
                if user is not None:
                    login(request,user,backend='store.customauth.EmailBackend')
                    del request.session['otp']
                    del request.session['otp_user']
                    return redirect('store:home')
        print(otpform.errors)
        return render(request,'store/otpverify.html',{'form':otpform,'error':'OTP verification failed'})
class RegisterView(View):
    def get(self,request):
        return render(request,'store/register.html',{'form':RegisterForm})
    def post(self,request):
        register_user=RegisterForm(request.POST)
        if register_user.is_valid():
            register_user.save()
            return redirect('store:login')
        return render(request,'store/register.html',{'form':RegisterForm})
@method_decorator(login_required(login_url='store:login'),name="dispatch")
class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('store:login')
class ConfirmEmail(View):
    def get(self,request,token):
        user_match=get_object_or_404(EmailTokenGeneration,token=token)
        user=user_match.user
        if user.is_active:
            return HttpResponse("Your email has already been confirmed.")
        else:
            user.is_active=True
            user.save()
            return render(request,'store/email_sucess.html')
@method_decorator(login_required(login_url='store:login'),name="dispatch")
class BookDetail(View):
    def get(self,request,book_id):
        book=Book.objects.get(id=book_id)
        comments=Comment.objects.filter(book=book_id)
        return render(request,'store/bookdetail.html',{'book':book,'comments':comments})
    def post(self,request,book_id):
        comment_value=request.POST.get('comment')
        book=Book.objects.get(id=book_id)
        comment_creation=Comment.objects.create(value=comment_value,comment_user=request.user,book=book)
        comment_creation.save()
        comments=Comment.objects.filter(book=book_id)
        return render(request,'store/bookdetail.html',{'book':book,'comments':comments})

store/templates/store/bookdetail.html
{% extends 'index.html' %}
{% block content %}
{% include 'storenavbar.html' %}
<div class="container mt-4">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <div class="card my-2 mx-lg-2 mx-md-2" style="width: 40rem;">
                <img src="{{book.book_image.url}}" class="card-img-top" alt="{{book.title}}">
                <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <p class="card-text">Author:{{book.author}}</p>
                <p class="card-text">{{book.description}}</p>
                <p class="card-text">Price:{{book.price}}</p>
                <form method="post" action="{% url 'store:bookdetail' book.id %}">
                    {% csrf_token %}
                    <label for="comment_id">Comment:</label>
                    <textarea name="comment" id="comment_id" cols="30" rows="10" class="form-control"></textarea>
                    <input type="submit" class="btn btn-primary mt-2" value="Comment">
                </form>
            </div>
            <div class="card my-2 mx-lg-2 mx-md-2 p-3">
                <h6>Comments:</h6>
                {% if comments %}
                    {% for comment in comments %}
                        <p><strong>{{comment.comment_user}}: </strong>{{comment.value}}</p>
                    {% endfor %}
                {% else %}
                    <p>No comments</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/cart.html
{% extends 'index.html' %}
{% block content %}
<nav class="navbar bg-dark border-bottom border-body" style="height: 4rem;" data-bs-theme="dark">
    <div class="container">
        <div>
            <a href="{% url 'store:home' %}" class="mx-2"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
              </svg></a>
            <a class="navbar-brand" href="#">Mero Cart</a>
        </div>
    </div>
</nav>
<div class="container mt-4">
    <h4>Cart Items:</h4>
    <div class="justify-content-center">
        {% for cart_item_id, book_values in cart.items %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{book_values.book_image}}" class="img-fluid rounded-start" alt="{{ book_values.title }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                        <h5 class="card-title">{{ book_values.title }}</h5>
                        <p class="card-text">Price:<small class="text-body-secondary">{{ book_values.price }}</small></p>
                        <p class="card-text">Quantity:<small class="text-body-secondary">{{ book_values.quantity }}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <form method="post" action="{% url 'store:cart' %}">
        {% csrf_token %}
        <label for="coupon_id">Enter coupons: </label>
        <input type="text" placeholder="Enter coupons code" name="coupon" id="coupon_id" class="form-control">
        <input class="btn btn-success d-block mt-1" type="submit" value="Checkout">
    </form>
</div>
{% endblock %}

store/templates/store/email_confirm.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
    <h1>Email Confirmation</h1>
    <p>Hello {{ user.username }},</p>
    <p>Thank you for registering. Please click the link below to confirm your email address:</p>
    <p><a href="{{ confirm_url }}">Confirm Email</a></p>
    <p>If you didn't register an account on our website, you can safely ignore this email.</p>
</body>
</html>

store/templates/store/email_sucess.html
{% extends 'index.html' %}
{% block content %}
    <p>User Email Confirmation Sucessful</p>
    <p>Go to HomePage: <a href="{% url 'store:home' %}">Home</a></p>
{% endblock%}

store/templates/store/home.html
{% extends 'index.html' %}
{% block content %}
{% include 'storenavbar.html' %}
<div class="container mt-4">
    <form action="{% url 'store:home' %}" method="get">
        <div class="form-group">
            <label for="genre" class="col-form-label">Filter By Genre:</label>
            <select class="form-select" name="genre" id="genre" required>
                <option value="" hidden selected disabled>Select an Option</option>
              {% for g in genre %}
              <option value="{{ g.id }}">{{ g.name }}</option>
              {% endfor %}
            </select>
        </div>
        <input type="submit" value="Filter" class="btn btn-primary my-2">
    </form>
    <h5>Avaliable Books</h5>
    <div class="row">
        <div class="col d-lg-flex d-md-flex flex-wrap d-block">
            {% for book in books %}
                <div class="card my-2 mx-lg-2 mx-md-2" style="width: 20rem;">
                    <img src="{{book.book_image.url}}" class="card-img-top" alt="{{book.title}}">
                    <div class="card-body">
                    <h5 class="card-title">{{book.title}}</h5>
                    <p class="card-text">Author:{{book.author}}</p>
                    <p class="card-text">{{book.description}}</p>
                    <p class="card-text">Price:{{book.price}}</p>
                    <form method="post" action="{% url 'store:home' %}">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book.id }}">
                        <input type="submit" class="btn btn-primary" value="Add to cart">
                    </form>
                    <button class="btn btn-primary mt-1"><a href="{% url 'store:bookdetail' book.id %}" class="text-decoration-none text-white">Detail</a></button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% if messages %}
    <script>
        alert("{{ messages }}");
    </script>
{% endif %}
{% endblock %}

store/templates/store/otpverify.html
{% extends 'index.html' %}
{% block title %}OTP Verification{% endblock %}
{% block content %}
<div class="row d-flex vh-100 align-items-center justify-content-center">
    <div class="col-sm-8 col-lg-3 col-md-6 col-10">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">OTP Form</h1>
                {% if error %}
                    <p class="bg-warning">{{error}}</p>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Verify" class="btn btn-secondary">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/register.html
{% extends 'index.html' %}
{% block content %}
<div class="row d-flex vh-100 align-items-center justify-content-center">
    <div class="col-sm-8 col-lg-4 col-md-6 col-10">
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">Register Form</h1>
                <form method="post" action="{% url 'store:register' %}">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Register" class="btn btn-secondary">
                </form>
                <p class="mt-3">Already Registered! <a href="{% url 'store:login' %}">Click Here</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}