bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('storeadmin/',include('storeadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *
app_name="store"
urlpatterns=[
    path('',HomeView.as_view(),name="home"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('cart/',CartView.as_view(),name="cart"),
    path('register/',RegisterView.as_view(),name="register"),
    path('confirm-email/<str:token>/',ConfirmEmail.as_view(),name="confirm"),
    path('login/otpcode/',OTPVerification.as_view(),name="otpverify"),
    path('bookdetail/<int:book_id>/',BookDetail.as_view(),name="bookdetail"),
]

storeadmin/urls.py
from django.urls import path
from .views import *
app_name="storeadmin"
urlpatterns=[
    path('addbook/',AddBookView.as_view(),name="addbook"),
    path('addauthor/',AddAuthor.as_view(),name="addauthor"),
    path('addgenre/',AddGenre.as_view(),name="addgenre"),
    path('login/',stafflogin.as_view(),name="stafflogin"),
    path('',StoreAdminPanel.as_view(),name="storepanel"),
    path('logout/',staffLogout.as_view(),name="logout"),
]

templates/adminnav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'storeadmin:storepanel' %}">Book Admin</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'storeadmin:storepanel' %}">Panel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'storeadmin:addbook' %}">Add Book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'storeadmin:addgenre' %}">Add Genre</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'storeadmin:addauthor' %}">Add Author</a>
          </li>
          <li class="nav-item">
            <a class="nav-link bg-danger" href="{% url 'storeadmin:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mero Books{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mero Books{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="row d-flex vh-100 align-items-center justify-content-center">
        <div class="col-sm-8 col-lg-3 col-md-6 col-10">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center">Login Form</h1>
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Login" class="btn btn-secondary">
                    </form>
                    <p class="mt-3">Not registered! <a href="{% url 'store:register' %}">Click Here</a></p>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/storenavbar.html
<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'store:home' %}">Mero Books</a>
          <form class="d-flex" role="search" method="get" action="{% url 'store:home' %}">
            <input class="form-control me-2" type="search" name="searckBook" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          <div class="p-1">
            <a href="{% url 'store:cart' %}" class="d-inline-block mx-2"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-bag" viewBox="0 0 16 16">
              <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
            </svg></a>
            <a href="{% url 'store:logout' %}" class="d-inline-block mx-2"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0z"/>
              <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
            </svg></a>
          </div>
      </div>
</nav>